# Generated by Django 5.1.9 on 2026-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="marketplace_visible",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="When True, this product appears in the cross-vendor Sellora marketplace (/api/v1/marketplace/products/), subject to the business-level show_in_marketplace flag also being True. Set to False to keep the product on the individual storefront only.",
            ),
        ),
    ]
