# Generated by Django 5.1.9 on 2026-09-12 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier used in storefront URLs e.g. /store/maison-aura/', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('cosmetics', 'Cosmetics'), ('perfumes', 'Perfumes'), ('fashion', 'Fashion'), ('accessories', 'Accessories'), ('beauty', 'Beauty'), ('gifts', 'Gifts'), ('electronics', 'Electronics'), ('food', 'Food & Beverages'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('motto', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.URLField(blank=True, default='', max_length=500)),
                ('favicon', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('growth', 'Growth')], default='starter', max_length=20)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('hero', models.JSONField(blank=True, default=dict)),
                ('about_text', models.TextField(blank=True, default='')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses_business',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_on_new_order', models.BooleanField(default=True)),
                ('email_on_low_stock', models.BooleanField(default=True)),
                ('email_on_new_message', models.BooleanField(default=True)),
                ('sms_on_new_order', models.BooleanField(default=False)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
                'db_table': 'businesses_settings',
            },
        ),
        migrations.CreateModel(
            name='StorefrontSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('featured_product_ids', models.JSONField(blank=True, default=list)),
                ('featured_category_ids', models.JSONField(blank=True, default=list)),
                ('show_new_arrivals', models.BooleanField(default=True)),
                ('show_best_sellers', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_settings', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Storefront Settings',
                'verbose_name_plural': 'Storefront Settings',
                'db_table': 'businesses_storefront_settings',
            },
        ),
    ]
