# Generated by Django 5.1.9 on 2026-09-17 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="E.164 format, e.g. +254712345678", max_length=20
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="Meta phone_number_id (from Business Manager)",
                        max_length=50,
                    ),
                ),
                (
                    "waba_id",
                    models.CharField(
                        help_text="WhatsApp Business Account ID", max_length=50
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="System-user permanent token. Treat as a secret."
                    ),
                ),
                (
                    "webhook_verify_token",
                    models.CharField(
                        help_text="Random string registered in Meta App → Webhooks → Verify Token",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_settings",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Settings",
                "verbose_name_plural": "WhatsApp Settings",
                "db_table": "businesses_whatsapp_settings",
            },
        ),
    ]
