# Generated by Django 5.1.9 on 2026-09-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_whatsapp_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="delivery_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="free_delivery_threshold",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="pickup_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
