# Generated by Django 5.1.9 on 2026-10-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_add_delivery_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontsettings",
            name="show_in_marketplace",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
