
from django.db import models

from apps.core.models import BaseModel


class ChatVisitor(BaseModel):
    """
    Represents someone visiting a business storefront.

    A visitor can chat anonymously using the UUID generated by BaseModel.
    Name and email are optional and can be supplied by the visitor.
    """

    business = models.ForeignKey(
        "businesses.Business",
        on_delete=models.CASCADE,
        related_name="chat_visitors",
        db_index=True,
    )

    name = models.CharField(
        max_length=255,
        blank=True,
        default="",
    )

    email = models.EmailField(
        blank=True,
        default="",
    )

    phone = models.CharField(
        max_length=30,
        blank=True,
        default="",
        help_text="Optional phone number supplied by the visitor during chat intro.",
    )

    class Meta:
        db_table = "messages_chat_visitor"
        verbose_name = "Chat Visitor"
        verbose_name_plural = "Chat Visitors"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["business", "created_at"]),
        ]

    def __str__(self):
        if self.name:
            return f"{self.name} ({self.id})"

        return f"Visitor {self.id}"

