# Generated by Django 5.1.9 on 2026-09-12 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=30)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('contact_form', 'Contact Form'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], db_index=True, default='contact_form', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], db_index=True, default='unread', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Customer Message',
                'verbose_name_plural': 'Customer Messages',
                'db_table': 'messages_customer_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='messages_cu_busines_88d693_idx')],
            },
        ),
    ]
