# Generated by Django 5.1.9 on 2026-09-17 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_whatsapp_settings"),
        ("customer_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        help_text="E.164 format received from Meta webhook e.g. 254712345678",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("awaiting_reply", "Awaiting Reply"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "service_window_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datetime when the free-reply service window closes",
                        null=True,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("unread_count", models.PositiveIntegerField(default=0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_whatsapp_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_conversations",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Conversation",
                "verbose_name_plural": "WhatsApp Conversations",
                "db_table": "messages_whatsapp_conversation",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "whatsapp_message_id",
                    models.CharField(
                        db_index=True,
                        help_text="Meta wamid — e.g. wamid.HBgL...",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("sticker", "Sticker"),
                            ("template", "Template"),
                            ("unknown", "Unknown"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(blank=True, default="")),
                ("media_id", models.CharField(blank=True, default="", max_length=100)),
                ("media_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "media_mime_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "media_caption",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("received", "Received"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=10,
                    ),
                ),
                ("message_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="customer_messages.whatsappconversation",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_whatsapp_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
                "db_table": "messages_whatsapp_message",
                "ordering": ["message_timestamp", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["business", "status"], name="messages_wh_busines_495d59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["business", "customer_phone"],
                name="messages_wh_busines_302463_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappconversation",
            constraint=models.UniqueConstraint(
                fields=("business", "customer_phone"),
                name="unique_whatsapp_conversation_per_customer",
            ),
        ),
    ]
