# Generated by Django 5.1.9 on 2026-10-03 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_add_delivery_settings"),
        ("customer_messages", "0002_whatsapp_conversation_and_message"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatVisitor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_visitors",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_visitors",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Visitor",
                "verbose_name_plural": "Chat Visitors",
                "db_table": "messages_chat_visitor",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to="businesses.business",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="customer_messages.chatvisitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Conversation",
                "verbose_name_plural": "Chat Conversations",
                "db_table": "messages_chat_conversation",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("visitor", "Visitor"), ("business", "Business")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="customer_messages.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "messages_chat_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="messages_ch_convers_c2b5d5_idx",
                    ),
                    models.Index(
                        fields=["conversation", "is_read"],
                        name="messages_ch_convers_50b523_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chatvisitor",
            index=models.Index(
                fields=["business", "customer"], name="messages_ch_busines_f2e46b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["business", "status"], name="messages_ch_busines_501595_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["visitor", "status"], name="messages_ch_visitor_b3e86c_idx"
            ),
        ),
    ]
