# Generated by Django 5.1.9 on 2026-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_add_delivery_settings"),
        ("customer_messages", "0003_chatvisitor_chatconversation_chatmessage_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatvisitor",
            name="messages_ch_busines_f2e46b_idx",
        ),
        migrations.RemoveField(
            model_name="chatvisitor",
            name="customer",
        ),
        migrations.AddIndex(
            model_name="chatvisitor",
            index=models.Index(
                fields=["business", "created_at"], name="messages_ch_busines_94f3df_idx"
            ),
        ),
    ]
