# Generated by Django 5.1.9 on 2026-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_messages",
            "0004_remove_chatvisitor_messages_ch_busines_f2e46b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatvisitor",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional phone number supplied by the visitor during chat intro.",
                max_length=30,
            ),
        ),
    ]
