# Generated by Django 5.1.9 on 2026-09-17 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0002_whatsapp_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("mpesa", "M-Pesa")], default="mpesa", max_length=30
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("paybill", "PayBill"), ("till", "Till Number")],
                        max_length=30,
                    ),
                ),
                (
                    "paybill_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "paybill_account_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "till_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_configuration",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
