# Generated by Django 5.1.9 on 2026-09-19 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_add_delivery_settings"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "checkout_request_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("phone", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cart_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("callback_payload", models.JSONField(blank=True, null=True)),
                (
                    "result_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "result_desc",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_transactions",
                        to="businesses.business",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpesa_transaction",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "M-Pesa Transaction",
                "verbose_name_plural": "M-Pesa Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
