# Generated by Django 5.1.9 on 2026-09-12 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('stock_purchases', 'Stock Purchases'), ('staff_salaries', 'Staff Salaries'), ('rent_utilities', 'Rent & Utilities'), ('marketing', 'Marketing'), ('delivery_costs', 'Delivery Costs'), ('equipment', 'Equipment'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'finances_expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
